import { createGitHubClient } from '../core/github.js';
import { llm, MODELS, buildMessages } from '../core/llm.js';
import { createLogger } from '../core/logger.js';
import { STANDUP_PROMPT } from './prompts.js';

async function main() {
  const github = createGitHubClient();
  const logger = createLogger();
  
  console.log('PM Agent generating daily standup...');
  
  try {
    const [openIssues, recentPRs, recentCommits] = await Promise.all([
      github.getOpenIssues(),
      github.getRecentPullRequests(10),
      github.getRecentCommits(10),
    ]);
    
    console.log(`Open issues: ${openIssues.length}`);
    console.log(`Recent PRs: ${recentPRs.length}`);
    console.log(`Recent commits: ${recentCommits.length}`);
    
    const inProgress = openIssues.filter(i => 
      i.labels.some(l => l.name === 'status:in-progress')
    );
    
    const blocked = openIssues.filter(i => 
      i.labels.some(l => l.name === 'status:blocked' || l.name === 'human:needed')
    );
    
    const ready = openIssues.filter(i => 
      i.labels.some(l => l.name === 'status:ready')
    );
    
    const openIssuesText = openIssues.map(i => 
      `#${i.number}: ${i.title} [${i.labels.map(l => l.name).join(', ')}]`
    ).join('\n');
    
    const prsText = recentPRs.map(pr => 
      `#${pr.number}: ${pr.title} (${pr.state})`
    ).join('\n');
    
    const commitsText = recentCommits.map(c => 
      `${c.sha}: ${c.message.split('\n')[0]}`
    ).join('\n');
    
    const standupPrompt = STANDUP_PROMPT
      .replace('{{openIssues}}', openIssuesText || 'None')
      .replace('{{recentPRs}}', prsText || 'None')
      .replace('{{recentCommits}}', commitsText || 'None');
    
    const report = await llm.complete({
      model: MODELS.quick,
      messages: buildMessages('You write concise project status reports.', standupPrompt),
      maxTokens: 1000,
    });
    
    const today = new Date().toISOString().split('T')[0];
    
    let standupBody = `## Daily Standup - ${today}\n\n`;
    standupBody += report.content;
    standupBody += `\n\n---\n`;
    standupBody += `### Quick Stats\n`;
    standupBody += `| Metric | Count |\n|--------|-------|\n`;
    standupBody += `| Open Issues | ${openIssues.length} |\n`;
    standupBody += `| In Progress | ${inProgress.length} |\n`;
    standupBody += `| Blocked | ${blocked.length} |\n`;
    standupBody += `| Ready for Dev | ${ready.length} |\n`;
    standupBody += `| Open PRs | ${recentPRs.filter(p => p.state === 'open').length} |\n`;
    standupBody += `\n*Generated by PM Agent*`;
    
    const standupIssue = await github.createIssue(
      `Daily Standup - ${today}`,
      standupBody,
      ['standup', 'automated']
    );
    
    console.log(`Standup created: #${standupIssue.number}`);
    
    await logger.log({
      agent: 'pm',
      action: 'daily_standup',
      issueNumber: standupIssue.number,
      success: true,
      details: {
        openIssues: openIssues.length,
        inProgress: inProgress.length,
        blocked: blocked.length,
      },
    });
    
    console.log('PM Agent standup completed!');
    
  } catch (error) {
    console.error('Standup generation failed:', error);
    
    await logger.log({
      agent: 'pm',
      action: 'standup_error',
      success: false,
      error: error.message,
    });
    
    process.exit(1);
  }
}

main();
